language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - PYTHONPATH="src"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install ipaddress; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install ipaddress; fi
  - 'pip install pyzmq'
  - 'pip install https://github.com/zeromq/pyre/archive/master.zip'
branches:
  only:
    - master
script: python -m unittest -v tests/test_zocp.py
